# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Include include_high_availability_config.yml vars
  block:
    - name: Include include_high_availability_config vars
      ansible.builtin.include_vars: "{{ ha_config_file }}"
      register: include_ha_config
      no_log: true
  rescue:
    - name: Failed to include_high_availability_config.yml
      ansible.builtin.fail:
        msg: "{{ ha_config_syntax_fail_msg }} Error: {{ include_ha_config.message }}"

- name: Set high_availability_status
  ansible.builtin.set_fact:
    enable_k8s_ha: "{{ include_ha_config.ansible_facts.k8s_head_node_ha.enable_k8s_ha | default(false) }}"
    k8s_vip: "{{ include_ha_config.ansible_facts.k8s_head_node_ha.virtual_ip_address }}"
    external_lb_ip: "{{ include_ha_config.ansible_facts.k8s_head_node_ha.external_loadbalancer_ip }}"
    lb_port: "{{ include_ha_config.ansible_facts.k8s_head_node_ha.loadbalancer_port }}"

- name: Validate virtual_ip_address details when enable_k8s_ha is provided
  ansible.builtin.assert:
    that:
      - k8s_vip is defined
      - k8s_vip | length > 1
    fail_msg: "{{ ha_vip_address_fail_msg }}"
  when: enable_k8s_ha
