# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Notify if no new service nodes were discovered
  when:
    - discovered_service_nodes is defined
    - discovered_service_nodes | length < 1
  block:
    - name: Warning - No new service node got discovered
      ansible.builtin.pause:
        prompt: "{{ no_service_node_msg }}"
        seconds: "{{ warning_time_10 }}"

- name: Update PostgreSQL configuration file and restart PostgreSQL
  when: discovered_service_nodes | length > 0
  block:
    - name: Update PostgreSQL configuration file with service node IPs
      ansible.builtin.lineinfile:
        path: "{{ pg_hba_conf_path }}"
        line: "host    all          all        {{ item.admin_ip }}/32      md5"
        state: present
        regexp: "^host\\s+all\\s+all\\s+{{ item.admin_ip }}/32\\s+md5$"
      loop: "{{ discovered_service_nodes }}"
      loop_control:
        label: "{{ item.admin_ip }}"

    - name: Update PostgreSQL configuration file with service node Virtual IPs
      ansible.builtin.lineinfile:
        path: "{{ pg_hba_conf_path }}"
        line: "host    all          all        {{ item.virtual_ip_address }}/32      md5"
        state: present
        regexp: "^host\\s+all\\s+all\\s+{{ item.virtual_ip_address }}/32\\s+md5$"
      loop: "{{ service_node_ha_data.service_nodes }}"
      loop_control:
        label: "{{ item.virtual_ip_address }}"
      when:
        - enable_service_ha | default(false)
        - service_node_ha_data.service_nodes | length > 0
        - item.virtual_ip_address is defined
        - item.virtual_ip_address | length > 0

    - name: Restart PostgreSQL
      ansible.builtin.service:
        name: postgresql
        state: restarted
      become: true
