#  Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---
- name: Install common packages
  ansible.builtin.package:
    name: "{{ common_packages[ansible_os_family] }}"
    state: present

- name: Firewall service running
  ansible.builtin.systemd_service:
    name: firewalld
    state: started
    enabled: true

# - name: Set firewall default zone as trusted
#   ansible.builtin.command: firewall-cmd --set-default-zone=trusted
#   changed_when: true

# - name: Reload firewalld
#   ansible.builtin.command: firewall-cmd --reload
#   changed_when: true

- name: Add Ports to Firewall for control plane
  ansible.posix.firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop: "{{ k8s_firewall_ports_list['kube_control_plane'] }}"
  when: '"kube_control_plane" in group_names'

- name: Add Ports to Firewall for node
  ansible.posix.firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop: "{{ k8s_firewall_ports_list['kube_node'] }}"
  when: '"kube_node" in group_names'

- name: Add Ports to Firewall for etcd
  ansible.posix.firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop: "{{ k8s_firewall_ports_list['etcd'] }}"
  when: '"etcd" in group_names'

- name: Enable http/https services
  ansible.posix.firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop: "{{ web_services }}"
