# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Execute utility tasks
  block:
    - name: Check if certificate path exists for all user registries
      ansible.builtin.stat:
        path: "{{ containerd_cert_path }}"
      register: directory_check
      failed_when: false

    - name: Create new directory if path does not exist
      ansible.builtin.file:
        path: "{{ containerd_cert_path }}"
        state: directory
        mode: "{{ mode }}"
      when: not directory_check.stat.exists
      failed_when: false

    - name: Check if _default directory exists
      ansible.builtin.stat:
        path: "{{ containerd_cert_path }}/_default"
      register: dir_chk

    - name: Create _default directory if doesn't exist
      ansible.builtin.file:
        path: "{{ containerd_cert_path }}/_default"
        state: directory
        mode: "{{ mode }}"
      when: not dir_chk.stat.exists

    - name: Set fact admin ip
      ansible.builtin.set_fact:
        admin_ip: "{{ hostvars['localhost']['admin_nic_ip'] }}"

    - name: Ensure _default/hosts.toml is overwritten or created from template
      ansible.builtin.template:
        src: "{{ update_registry_template_src }}"
        dest: "{{ containerd_cert_path }}/_default/hosts.toml"
        mode: "{{ file_permissions }}"  # Set permissions as needed

    - name: Restart containerd
      ansible.builtin.systemd:
        name: containerd
        state: restarted
        enabled: true
