# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Login node configless
  when: slurm_installation_type == configless_slurm
  block:
    - name: Install login packages
      ansible.builtin.package:
        name: "{{ slurm_login_packages[ansible_os_family] }}"
        state: present

    - name: Get slurm conf from controller
      ansible.posix.synchronize:
        src: "{{ slurm_share_prefix }}{{ slurm_config_dir }}/slurm.conf"
        dest: "{{ slurm_share_prefix }}{{ slurm_config_dir }}/"
        mode: push
        checksum: true
      delegate_to: "{{ groups['slurm_control_node'] | first }}"

    - name: Set env variable
      community.general.ini_file:
        path: "{{ sys_env_path }}"
        option: SLURM_CONF
        value: "{{ slurm_share_prefix }}{{ slurm_config_dir }}/slurm.conf"
        no_extra_spaces: true
        mode: u=rw,g=r,o=r

    - name: Remove PATH env variable
      community.general.ini_file:
        path: "{{ sys_env_path }}"
        option: PATH
        state: absent
        mode: u=rw,g=r,o=r

    # Below is slurmd daemon install as per slurm guide
    - name: Install compute packages
      ansible.builtin.package:
        name: "{{ slurm_compute_packages[ansible_os_family] }}"
        state: present

    - name: Enable SlurmdPort for login node # login
      ansible.posix.firewalld:
        port: "{{ slurm_conf_dict['SlurmdPort'] }}/tcp"
        permanent: true
        state: enabled
        immediate: true

    - name: Enable the service
      ansible.builtin.service:
        name: slurmd
        enabled: true
      register: slurmd_service

    - name: Get service path
      ansible.builtin.set_fact:
        slurmd_service_path: "{{ slurmd_service['status']['FragmentPath'] | default(slurmd_service_default_path) }}"

    - name: Edit the service ConditionPathExists
      community.general.ini_file:
        path: "{{ slurmd_service_path }}"
        section: Unit
        option: ConditionPathExists
        owner: "{{ root_user }}"
        group: "{{ root_group }}"
        mode: "{{ conf_file_mode }}"
        state: absent

    - name: Edit the service ExecStart
      community.general.ini_file:
        path: "{{ slurmd_service_path }}"
        section: Service
        option: ExecStart
        owner: "{{ root_user }}"
        group: "{{ root_group }}"
        mode: "{{ conf_file_mode }}"
        value: "/usr/sbin/slurmd -D
         --conf-server {{ (hostvars[groups['slurm_control_node'] | first])['inventory_hostname_short']
         + ':' + (slurm_conf_dict['SlurmctldPort'] | string) }} -s $SLURMD_OPTIONS" # HA

    - name: Reload slurmd # No handlers as not slurmd
      ansible.builtin.systemd_service:
        name: slurmd
        state: reloaded
        daemon_reload: true
        enabled: true
      when: restart_slurm_services

    - name: Restart slurmd
      ansible.builtin.systemd_service:
        name: slurmd
        state: restarted
      when: restart_slurm_services

- name: Login node nfs_share
  when: slurm_installation_type == nfs_share_slurm
  block:
    - name: Set env variable
      community.general.ini_file:
        path: "{{ sys_env_path }}"
        option: SLURM_CONF
        value: "{{ slurm_share_prefix }}{{ slurm_config_dir }}/slurm.conf"
        no_extra_spaces: true
        mode: u=rw,g=r,o=r

    - name: Check current environment variables
      ansible.builtin.shell: echo $PATH # noqa: command-instead-of-shell
      changed_when: false
      register: path_output

    - name: Set env variable
      community.general.ini_file:
        path: "{{ sys_env_path }}"
        option: PATH
        value: "{{ path_output.stdout }}:{{ slurm_share_prefix }}usr/bin:{{ slurm_share_prefix }}usr/sbin"
        no_extra_spaces: true
        mode: u=rw,g=r,o=r
