# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Perform operations for static range
  when: bmc_static_status
  block:
    - name: BMC discover for the group
      ansible.builtin.include_tasks: bmc_group_discovery.yml
      when:
        - item.value.bmc_static_status is defined
        - item.value.bmc_static_status
      loop: "{{ groups_roles_info | dict2items }}"

- name: Perform operations for dynamic range
  when:
    - discovery_mech_dynamic_bmc
  block:
    - name: Configure dhcp
      ansible.builtin.include_tasks: "{{ role_path }}/../oim/tasks/configure_dhcp.yml"

    - name: Before starting dynamic discovery wait for "{{ dhcp_timeout }}"
      ansible.builtin.pause:
        seconds: "{{ dhcp_timeout }}"
        prompt: "{{ dhcp_timeout_msg }}"

    - name: Enable IPMI on dynamic iDRACs
      ansible.builtin.include_tasks: dynamic_ipmi_enable.yml

    - name: Perform BMC Discover on dynamic range
      ansible.builtin.include_tasks: bmc_dynamic_discovery.yml

    - name: Update node objects for dynamic bmc_mode
      ansible.builtin.include_tasks: update_db_dynamic.yml
      when: dynamic_final_status

    - name: Update node objects for static bmc mode
      ansible.builtin.include_tasks: update_node_obj.yml
      when: dynamic_final_status

    - name: Delete the stanzas file
      ansible.builtin.include_tasks: delete_stanzas.yml

- name: Common tasks for bmc static and dynamic discovery
  when: bmc_static_status or discovery_mech_dynamic_bmc
  block:
    - name: Configure dhcp
      ansible.builtin.include_tasks: "{{ role_path }}/../oim/tasks/configure_dhcp.yml"
