# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Set variables for LTB role path
  ansible.builtin.set_fact:
    ltb_repo_path: "{{ ldap_dir }}/{{ ltb_git_repo_path }}"

- name: Check certificate files exist
  ansible.builtin.stat:
    path: "{{ ltb_repo_path }}"
  register: dir_status

- name: Fail if LTB role directory doesn't exist
  ansible.builtin.fail:
    msg: "{{ fail_msg_ltb_dir }}"
  when: not dir_status.stat.exists

- name: Validate Certificate directory
  when:
    - tls_ca_certificate != ''
    - tls_certificate != ''
    - tls_certificate_key != ''
  block:
    - name: Check certificate files exist
      ansible.builtin.stat:
        path: "{{ item }}"
      register: file_status
      failed_when: not file_status.stat.exists
      loop:
        - "{{ tls_ca_certificate }}"
        - "{{ tls_certificate }}"
        - "{{ tls_certificate_key }}"
  rescue:
    - name: Certificate path invalid
      ansible.builtin.fail:
        msg: "{{ ldap_cert_path_fail_msg }}"
