#  Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Kubernetes Installation
  hosts: localhost
  tasks:
    - name: Set k8s_var_input based on k8s_var_file_flag (default to false if not defined)
      ansible.builtin.set_fact:
        k8s_var_input: "{{ 'k8s_all_ha_vars.yml' if (k8s_var_file_flag | default(false)) else 'k8s_all_non_ha_vars.yml' }}"

- name: Start Kubernetes Installations
  hosts: omnia_kubespray
  vars:
    kubespray_nfs_share: "/opt/omnia/kubespray"
    kubespray_logs_path: "/opt/omnia/log/kubespray/k8s_deployment.log"
    k8s_inv: "{{ kubespray_nfs_share }}/{{ hostvars['127.0.0.1']['k8s_var_input'] }}"
    dir_mode: '0755'
  tasks:
    - name: Install Kubernetes using kubespray
      when:
        - hostvars['127.0.0.1']['k8s_support']
      block:
        - name: Copy k8s_start_setup to kubespray nfs share
          ansible.builtin.copy:
            src: "{{ playbook_dir }}/k8s_start_setup.yml"
            dest: "{{ kubespray_nfs_share }}/k8s_start_setup.yml"
            mode: "{{ dir_mode }}"

        - name: Execute ansible-playbook for Kubernetes setup asynchronously
          ansible.builtin.shell: |
            set -o pipefail
            /venv/bin/ansible-playbook {{ kubespray_nfs_share }}/k8s_start_setup.yml \
            -i {{ kubespray_nfs_share }}/inv_k8s \
            --extra-vars "@{{ k8s_inv }}" -vvv | \
            /usr/bin/tee {{ kubespray_logs_path }}
          async: 3600  # Set async timeout (e.g., 1 hour)
          poll: 0  # Non-blocking (continue the playbook without waiting for completion)
          register: result  # Register the result to capture job ID
          changed_when: false

        - name: Wait for the Kubernetes installation to finish. Logs can be checked at {{ kubespray_logs_path }}
          ansible.builtin.async_status:
            jid: "{{ result.ansible_job_id }}"  # Job ID from the previous task
          register: job_result
          until: job_result.finished
          retries: 60  # Retry the task 60 times (10 min total)
          delay: 10  # Wait 10 seconds between retries
