
# Usage: fetch_software_config.yml
software_config_file: "{{ input_project_dir }}/software_config.json"
software_config_syntax_fail_msg: "Failed. Syntax errors present in software_config.json. Fix errors and re-run playbook again."
ha_config_file: "{{ input_project_dir }}/high_availability_config.yml"
ha_config_syntax_fail_msg: "Failed. Syntax errors present in high_availability_config.yml. Fix errors and re-run playbook again."

# Usage: validate_inventory.yml
empty_inventory_fail_msg: |
  "Failed. inventory not provided. Re-run playbook with inventory by providing -i inventory.
  Inventory support groups are slurm_control_node, slurm_node, slurm_dbd, login, kube_control_plane, kube_node, etcd, auth_server" 
cluster_layout_path: "/opt/omnia/omnia_inventory/cluster_layout"
warning_wait_time: 30
inventory_warn_msg: |
  "[WARNING] Inventory not provided. Omnia generated inventory detected at {{ cluster_layout_path }}.
   If roles details are provided in roles_config.yml, the generated inventory will be used and proceeding."

# Usage: k8s_validations.yml
invalid_kube_inventory_fail_msg: |
  "Failed. k8s software is present in software_config.json.
  Invalid inventory format, specify kube_control_plane, kube_node and etcd group in inventory and re-run playbook"
kube_one_node_validation_fail_msg: |
  "Failed. k8s software is present in software_config.json.
  There should be one entry for kube_control_plane in the inventory"
kube_control_plane_validation_fail_msg: |
  "Failed. k8s software is present in software_config.json.
  kube_control_plane group in inventory must have atleast one node and total node count must be odd"
kube_ha_setup_warning_msg: |
  "[WARNING] To ensure a clear leader election in a Kubernetes High Availability (HA) setup,
  configure the cluster with an odd number of kube_control_plane and etcd nodes (e.g., 3, 5, or 7). Proceeding execution with provided nodes."
kube_nonha_setup_warning_msg: |
  "[WARNING] In a non-HA setup with multiple control plane nodes and a single etcd node,
  if the etcd node fails, the entire Kubernetes cluster could experience downtime.Proceeding execution with provided nodes."
kube_one_node_validation_success_msg: |
  "kube_control_plane exists in the inventory"
kube_node_validation_fail_msg: |
  "Failed. k8s software is present in software_config.json.
  At least one kube_node should be present in the inventory."
kube_node_validation_success_msg: "At least one kube_node exists in the inventory"
etcd_node_validation_fail_msg: |
  "Failed. k8s software is present in software_config.json.
  etcd group in inventory must have atleast one node and total node count must be odd."
etcd_node_validation_success_msg: "etcd should have odd number of nodes in the inventory"
unreachable_kube_control_plane_fail_msg: |
  "Failed. Unreachable node mentioned in inventory for kube_control_plane.
  Re-run playbook with reachable kube_control_plane."

# Usage: slurm_validations.yml
invalid_slurm_inventory_fail_msg: |
  "Failed. slurm software is present in software_config.json.
  Invalid inventory format, specify slurm_control_node, slurm_dbd and slurm_node group in inventory and re-run playbook."
slurm_one_node_validation_fail_msg: |
  "Failed. slurm software is present in software_config.json.
  There should be exactly one entry for slurm_control_node in the inventory."
slurm_one_node_validation_success_msg: |
  "One slurm_control_node exists in the inventory"
  slurm_node_validation_fail_msg: "Failed. slurm software is present in software_config.json.
  At least one slurm_node should be present in the inventory."
slurm_node_validation_success_msg: "At least one slurm_node exists in the inventory"
unreachable_slurm_control_node_fail_msg: 
  "Failed. Unreachable node mentioned in inventory for slurm_control_node.
  Re-run playbook with reachable slurm_control_node."
slurm_control_node_in_login_fail_msg: "Failed. Node mentioned in slurm_control_node group should not be present in login group"
slurm_control_node_in_node_fail_msg: "Failed. Node mentioned in slurm_control_node group should not be present in slurm_node group"
multiple_login_node_fail_msg: "Failed. Currently only one login node supported in inventory"
warning_wait_time: 10
login_node_warning_msg: |
  "[WARNING] login group with ip for login node not present in the inventory.
  Proceeding execution with provided nodes"

# Usage: validate_inventory.yml
invalid_auth_server_inventory_fail_msg: 
  "Failed. openldap or freeipa software is present in software_config.json.
  Invalid inventory format, specify auth_sever group in inventory and re-run playbook."
auth_server_group_fail_msg: "Failed, auth_server group should contain exactly 1 node"
auth_server_group_success_msg: "Success, inventory file is valid"
